# pull official base image
FROM python:3.8.0-alpine

# set work directory
WORKDIR /app

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# copy source files
COPY . /app/
