version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8081:8081"
    networks:
      - celerynet
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    networks:
      - celerynet
    ports:
      - "5673:5672"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-worker
    command: "celery worker -A proj.celery --loglevel=info"
    networks:
      - celerynet
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq

networks:
  celerynet:
